# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator_key_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 485)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 80, 61, 21))
        self.label.setObjectName("label")
        self.textEditDeviceId = QtWidgets.QTextEdit(Form)
        self.textEditDeviceId.setGeometry(QtCore.QRect(140, 80, 271, 31))
        self.textEditDeviceId.setObjectName("textEditDeviceId")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 47, 13))
        self.label_2.setObjectName("label_2")
        self.textEditKeyDuration = QtWidgets.QTextEdit(Form)
        self.textEditKeyDuration.setGeometry(QtCore.QRect(140, 150, 271, 31))
        self.textEditKeyDuration.setObjectName("textEditKeyDuration")
        self.plainTextKey = QtWidgets.QPlainTextEdit(Form)
        self.plainTextKey.setGeometry(QtCore.QRect(140, 220, 431, 151))
        self.plainTextKey.setObjectName("plainTextKey")
        self.cleanButton = QtWidgets.QPushButton(Form)
        self.cleanButton.setGeometry(QtCore.QRect(140, 400, 131, 51))
        self.cleanButton.setObjectName("cleanButton")
        self.generateKeyButton = QtWidgets.QPushButton(Form)
        self.generateKeyButton.setGeometry(QtCore.QRect(290, 400, 131, 51))
        self.generateKeyButton.setObjectName("generateKeyButton")
        self.sendKeyButton = QtWidgets.QPushButton(Form)
        self.sendKeyButton.setGeometry(QtCore.QRect(440, 400, 131, 51))
        self.sendKeyButton.setObjectName("sendKeyButton")
        self.textEditMail = QtWidgets.QTextEdit(Form)
        self.textEditMail.setGeometry(QtCore.QRect(140, 30, 271, 31))
        self.textEditMail.setObjectName("textEditMail")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 61, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Id Device:"))
        self.label_2.setText(_translate("Form", "Duration:"))
        self.cleanButton.setText(_translate("Form", "Clean"))
        self.generateKeyButton.setText(_translate("Form", "Generate Key"))
        self.sendKeyButton.setText(_translate("Form", "Send Key"))
        self.label_3.setText(_translate("Form", "Email:"))
